//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ShopId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ShopCode { get; set; }
        public string ShopName { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ExpirTime { get; set; }
        public string InUserID { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
