//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.InventoryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long AnswerId { get; set; }
        public int ProjectId { get; set; }
        public int ShopId { get; set; }
        public string VinCode { get; set; }
        public string VinCode8 { get; set; }
        public string ModelName { get; set; }
        public string SubModelName { get; set; }
        public string StockAge { get; set; }
        public string SaleFlag { get; set; }
        public string VinPhotoName { get; set; }
        public string SaleInvoicePhotoName { get; set; }
        public string CarBackPhotoName { get; set; }
        public string Remark { get; set; }
        public string AddChk { get; set; }
        public string ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public string InUserID { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
